### PR TITLE
Improve HttpClient errors

### PR DESCRIPTION
**Pull request by BMillman19**
This PR:

* Sanitize HttpClient api urls and improve error messaging

### CODE REVIEW

**Comment by LogvinovLeon** [comment]
Can we also try to prevent people from passing a v0 suffix as we add it ourselves?

**Comment by BMillman19** [comment]
@LogvinovLeon should we keep adding a v0 to the end of the passed in URL? an api url can implement standard relayer api v0 w/o having a v0 at the end of the path

**Comment by LogvinovLeon** [comment]
I think we shouldn't

**Comment by BMillman19** [comment]
Yea I agree, i will remove it

**Pull request merged**
