### PR TITLE
Add build:watch command to all TS packages

### PR DESCRIPTION
**Pull request by LogvinovLeon**
## Description

This PR adds a build:watch command to all TS packages so that you can recompile/watch all packages by just running: `lerna --parallel build:watch`

## Motivation and Context

Dev velocity

## How Has This Been Tested?

On my computer

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

* [ ] Change requires a change to the documentation.
* [ ] Added tests to cover my changes.

### CODE REVIEW

**Comment by dekz** [comment]
👍 

Can we throw `lerna --parallel build:watch` in the main package.json scripts so a dev can just run `yarn run lerna:watch` for example?

**Comment by BMillman19** [comment]
If we make a change in 0x.js will this automatically watch and rebuild dependent packages, like testnet-faucets for example?

**Comment by fabioberger** [comment]
Same q as @BMillman19.

**Comment by LogvinovLeon** [comment]
@BMillman19 @fabioberger Yes. It's not idead, cause sometimes building 0x.js involves multiple changes and it cascades multiple time, but after all - yes.

**Pull request merged**
